"""initial_schema

Revision ID: e6eff05803a7
Revises: 
Create Date: 2026-06-19 12:53:16.083139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6eff05803a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_origin_date'), table_name='origin_tracking')
    op.drop_index(op.f('idx_origin_source'), table_name='origin_tracking')
    op.drop_index(op.f('idx_origin_topic'), table_name='origin_tracking')
    op.drop_table('origin_tracking')
    op.drop_index(op.f('idx_watchlist_items_list'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('idx_saved_searches_user'), table_name='saved_searches')
    op.drop_table('saved_searches')
    op.drop_table('calibration_prompts')
    op.drop_table('watchlists')
    op.drop_index(op.f('idx_embeddings_vector'), table_name='article_embeddings', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('article_embeddings')
    op.alter_column('alerts', 'related_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('alerts', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('idx_alerts_date'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_type'), table_name='alerts')
    op.drop_index(op.f('idx_alerts_unread'), table_name='alerts', postgresql_where='(is_read = false)')
    op.drop_table_comment(
        'alerts',
        existing_comment='Svi alertovi platforme - koordinacija, anomalije, silence',
        schema=None
    )
    op.alter_column('anomalies', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('idx_anomalies_date'), table_name='anomalies')
    op.drop_index(op.f('idx_anomalies_type'), table_name='anomalies')
    op.drop_index(op.f('idx_analysis_analyzed'), table_name='article_analysis')
    op.drop_index(op.f('idx_analysis_article'), table_name='article_analysis')
    op.drop_index(op.f('idx_analysis_political'), table_name='article_analysis')
    op.drop_index(op.f('idx_analysis_topic'), table_name='article_analysis', postgresql_using='gin')
    op.drop_table_comment(
        'article_analysis',
        existing_comment='AI analiza svakog clanka - teme, pozicioniranje, sentiment. 1:1 sa articles',
        schema=None
    )
    op.drop_index(op.f('idx_article_entities_article'), table_name='article_entities')
    op.drop_index(op.f('idx_article_entities_entity'), table_name='article_entities')
    op.drop_table_comment(
        'article_entities',
        existing_comment='Veza clanak-entitet sa kontekstom pominjanja',
        schema=None
    )
    op.drop_index(op.f('idx_article_framings_article'), table_name='article_framings')
    op.drop_index(op.f('idx_article_framings_framing'), table_name='article_framings')
    op.drop_index(op.f('idx_article_narratives_article'), table_name='article_narratives')
    op.drop_index(op.f('idx_article_narratives_narrative'), table_name='article_narratives')
    op.drop_constraint(op.f('article_versions_article_id_version_key'), 'article_versions', type_='unique')
    op.drop_index(op.f('idx_article_versions_article'), table_name='article_versions')
    op.drop_table_comment(
        'article_versions',
        existing_comment='Istorija izmena clanaka. Cuva sve verzije kada scraper detektuje promenu content_hash',
        schema=None
    )
    op.alter_column('articles', 'schema_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_articles_content_hash'), table_name='articles')
    op.drop_index(op.f('idx_articles_fts'), table_name='articles', postgresql_using='gin')
    op.drop_index(op.f('idx_articles_published'), table_name='articles')
    op.drop_index(op.f('idx_articles_published_at'), table_name='articles')
    op.drop_index(op.f('idx_articles_scraped'), table_name='articles')
    op.drop_index(op.f('idx_articles_source_published'), table_name='articles')
    op.drop_index(op.f('idx_articles_source_scraped'), table_name='articles')
    op.drop_index(op.f('idx_articles_tags'), table_name='articles', postgresql_using='gin')
    op.drop_index(op.f('idx_articles_text_trgm'), table_name='articles', postgresql_ops={'text_content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_articles_title_trgm'), table_name='articles', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_articles_url_hash'), table_name='articles')
    op.create_unique_constraint(None, 'articles', ['url_hash'])
    op.drop_table_comment(
        'articles',
        existing_comment='Prikupljeni clanci - osnovna tabela platforme. ~3000 clanaka dnevno pri punom kapacitetu',
        schema=None
    )
    op.alter_column('calibration_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_calibration_article'), table_name='calibration_feedback')
    op.drop_index(op.f('idx_calibration_type'), table_name='calibration_feedback')
    op.drop_index(op.f('idx_calibration_unapplied'), table_name='calibration_feedback', postgresql_where='(applied_to_pipeline = false)')
    op.drop_index(op.f('idx_calibration_user'), table_name='calibration_feedback')
    op.drop_table_comment(
        'calibration_feedback',
        existing_comment='RLHF feedback istrazivaca za kalibraciju AI modela',
        schema=None
    )
    op.drop_index(op.f('idx_copypaste_article_a'), table_name='coordination_copypaste')
    op.drop_index(op.f('idx_copypaste_article_b'), table_name='coordination_copypaste')
    op.drop_index(op.f('idx_copypaste_score'), table_name='coordination_copypaste')
    op.drop_table_comment(
        'coordination_copypaste',
        existing_comment='Detektovani copy-paste parovi sa similarity scorom',
        schema=None
    )
    op.alter_column('coordination_framing', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('idx_framing_coord_date'), table_name='coordination_framing')
    op.drop_index(op.f('idx_framing_coord_score'), table_name='coordination_framing')
    op.alter_column('coordination_narrative', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('idx_narrative_coord_date'), table_name='coordination_narrative')
    op.drop_index(op.f('idx_narrative_coord_score'), table_name='coordination_narrative')
    op.alter_column('daily_summaries', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_entities_name_type'), table_name='entities')
    op.drop_index(op.f('idx_entities_political'), table_name='entities', postgresql_where='(is_political_actor = true)')
    op.drop_index(op.f('idx_entities_type'), table_name='entities')
    op.create_unique_constraint(None, 'entities', ['name', 'entity_type'])
    op.drop_table_comment(
        'entities',
        existing_comment='NER entiteti - osobe, organizacije, mesta. Normalizovani sa varijantama',
        schema=None
    )
    op.alter_column('framing_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_framing_types_topic'), table_name='framing_types')
    op.drop_table_comment(
        'framing_types',
        existing_comment='Tematski specificni framing tipovi. AI predlaze, istrazivac validira',
        schema=None
    )
    op.alter_column('narrative_daily_intensity', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.drop_index(op.f('idx_narrative_intensity_date'), table_name='narrative_daily_intensity')
    op.drop_index(op.f('idx_narrative_intensity_narrative'), table_name='narrative_daily_intensity')
    op.drop_table_comment(
        'narrative_daily_intensity',
        existing_comment='Dnevni intenzitet narativa po izvoru - osnova za longitudinalnu analizu',
        schema=None
    )
    op.alter_column('narratives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('narratives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_narratives_active'), table_name='narratives')
    op.drop_index(op.f('idx_narratives_type'), table_name='narratives')
    op.drop_table_comment(
        'narratives',
        existing_comment='Narativi - sistemski i tematski. Seeding iz istorijskih podataka',
        schema=None
    )
    op.drop_index(op.f('idx_scraper_runs_source'), table_name='scraper_runs')
    op.drop_index(op.f('idx_scraper_runs_status'), table_name='scraper_runs')
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_table_comment(
        'sources',
        existing_comment='Registar svih 20 medijskih izvora sa tehnickim i vlasnickim metapodacima',
        schema=None
    )
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'sources',
        'Registar svih 20 medijskih izvora sa tehnickim i vlasnickim metapodacima',
        existing_comment=None,
        schema=None
    )
    op.alter_column('sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_scraper_runs_status'), 'scraper_runs', ['status', sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('idx_scraper_runs_source'), 'scraper_runs', ['source_id', sa.literal_column('started_at DESC')], unique=False)
    op.create_table_comment(
        'narratives',
        'Narativi - sistemski i tematski. Seeding iz istorijskih podataka',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_narratives_type'), 'narratives', ['narrative_type'], unique=False)
    op.create_index(op.f('idx_narratives_active'), 'narratives', ['is_active'], unique=False)
    op.alter_column('narratives', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('narratives', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'narrative_daily_intensity',
        'Dnevni intenzitet narativa po izvoru - osnova za longitudinalnu analizu',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_narrative_intensity_narrative'), 'narrative_daily_intensity', ['narrative_id', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_narrative_intensity_date'), 'narrative_daily_intensity', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('narrative_daily_intensity', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_table_comment(
        'framing_types',
        'Tematski specificni framing tipovi. AI predlaze, istrazivac validira',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_framing_types_topic'), 'framing_types', ['topic_id'], unique=False)
    op.alter_column('framing_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'entities',
        'NER entiteti - osobe, organizacije, mesta. Normalizovani sa varijantama',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'entities', type_='unique')
    op.create_index(op.f('idx_entities_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('idx_entities_political'), 'entities', ['is_political_actor'], unique=False, postgresql_where='(is_political_actor = true)')
    op.create_index(op.f('idx_entities_name_type'), 'entities', ['name', 'entity_type'], unique=True)
    op.alter_column('entities', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('entities', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_summaries', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_index(op.f('idx_narrative_coord_score'), 'coordination_narrative', [sa.literal_column('coordination_score DESC')], unique=False)
    op.create_index(op.f('idx_narrative_coord_date'), 'coordination_narrative', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('coordination_narrative', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_index(op.f('idx_framing_coord_score'), 'coordination_framing', [sa.literal_column('coordination_score DESC')], unique=False)
    op.create_index(op.f('idx_framing_coord_date'), 'coordination_framing', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('coordination_framing', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_table_comment(
        'coordination_copypaste',
        'Detektovani copy-paste parovi sa similarity scorom',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_copypaste_score'), 'coordination_copypaste', [sa.literal_column('similarity_score DESC')], unique=False)
    op.create_index(op.f('idx_copypaste_article_b'), 'coordination_copypaste', ['article_id_b'], unique=False)
    op.create_index(op.f('idx_copypaste_article_a'), 'coordination_copypaste', ['article_id_a'], unique=False)
    op.create_table_comment(
        'calibration_feedback',
        'RLHF feedback istrazivaca za kalibraciju AI modela',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_calibration_user'), 'calibration_feedback', ['user_id'], unique=False)
    op.create_index(op.f('idx_calibration_unapplied'), 'calibration_feedback', ['applied_to_pipeline'], unique=False, postgresql_where='(applied_to_pipeline = false)')
    op.create_index(op.f('idx_calibration_type'), 'calibration_feedback', ['analysis_type', 'is_correct'], unique=False)
    op.create_index(op.f('idx_calibration_article'), 'calibration_feedback', ['article_id'], unique=False)
    op.alter_column('calibration_feedback', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_table_comment(
        'articles',
        'Prikupljeni clanci - osnovna tabela platforme. ~3000 clanaka dnevno pri punom kapacitetu',
        existing_comment=None,
        schema=None
    )
    op.drop_constraint(None, 'articles', type_='unique')
    op.create_index(op.f('idx_articles_url_hash'), 'articles', ['url_hash'], unique=True)
    op.create_index(op.f('idx_articles_title_trgm'), 'articles', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_articles_text_trgm'), 'articles', ['text_content'], unique=False, postgresql_ops={'text_content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_articles_tags'), 'articles', ['tags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_articles_source_scraped'), 'articles', ['source_id', sa.literal_column('scraped_at DESC')], unique=False)
    op.create_index(op.f('idx_articles_source_published'), 'articles', ['source_id', sa.literal_column('published_at DESC')], unique=False)
    op.create_index(op.f('idx_articles_scraped'), 'articles', [sa.literal_column('scraped_at DESC')], unique=False)
    op.create_index(op.f('idx_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('idx_articles_published'), 'articles', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index(op.f('idx_articles_fts'), 'articles', [sa.literal_column("to_tsvector('simple'::regconfig, (COALESCE(title, ''::text) || ' '::text) || COALESCE(text_content, ''::text))")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_articles_content_hash'), 'articles', ['content_hash'], unique=False)
    op.alter_column('articles', 'schema_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table_comment(
        'article_versions',
        'Istorija izmena clanaka. Cuva sve verzije kada scraper detektuje promenu content_hash',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_article_versions_article'), 'article_versions', ['article_id'], unique=False)
    op.create_unique_constraint(op.f('article_versions_article_id_version_key'), 'article_versions', ['article_id', 'version'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_article_narratives_narrative'), 'article_narratives', ['narrative_id'], unique=False)
    op.create_index(op.f('idx_article_narratives_article'), 'article_narratives', ['article_id'], unique=False)
    op.create_index(op.f('idx_article_framings_framing'), 'article_framings', ['framing_type_id'], unique=False)
    op.create_index(op.f('idx_article_framings_article'), 'article_framings', ['article_id'], unique=False)
    op.create_table_comment(
        'article_entities',
        'Veza clanak-entitet sa kontekstom pominjanja',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_article_entities_entity'), 'article_entities', ['entity_id'], unique=False)
    op.create_index(op.f('idx_article_entities_article'), 'article_entities', ['article_id'], unique=False)
    op.create_table_comment(
        'article_analysis',
        'AI analiza svakog clanka - teme, pozicioniranje, sentiment. 1:1 sa articles',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_analysis_topic'), 'article_analysis', ['topics'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_analysis_political'), 'article_analysis', ['political_score'], unique=False)
    op.create_index(op.f('idx_analysis_article'), 'article_analysis', ['article_id'], unique=False)
    op.create_index(op.f('idx_analysis_analyzed'), 'article_analysis', [sa.literal_column('analyzed_at DESC')], unique=False)
    op.create_index(op.f('idx_anomalies_type'), 'anomalies', ['anomaly_type', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_anomalies_date'), 'anomalies', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('anomalies', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.create_table_comment(
        'alerts',
        'Svi alertovi platforme - koordinacija, anomalije, silence',
        existing_comment=None,
        schema=None
    )
    op.create_index(op.f('idx_alerts_unread'), 'alerts', ['is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('idx_alerts_type'), 'alerts', ['alert_type', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_alerts_severity'), 'alerts', ['severity', sa.literal_column('date DESC')], unique=False)
    op.create_index(op.f('idx_alerts_date'), 'alerts', [sa.literal_column('date DESC')], unique=False)
    op.alter_column('alerts', 'date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)
    op.alter_column('alerts', 'related_ids',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('article_embeddings',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('article_embeddings_article_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('article_embeddings_pkey')),
    sa.UniqueConstraint('article_id', name=op.f('article_embeddings_article_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    comment='Vektorski embeddinzi clanaka za similarity search (copy-paste detekcija)'
    )
    op.create_index(op.f('idx_embeddings_vector'), 'article_embeddings', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('watchlists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('watchlists_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='watchlists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='watchlists_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('calibration_prompts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('analysis_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prompt_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('feedback_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('activated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_calibration_prompt_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('calibration_prompts_pkey')),
    sa.UniqueConstraint('analysis_type', 'version', name=op.f('calibration_prompts_analysis_type_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('saved_searches',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('query_params', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('last_run', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('saved_searches_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('saved_searches_pkey'))
    )
    op.create_index(op.f('idx_saved_searches_user'), 'saved_searches', ['user_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('watchlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('item_value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('watchlist_items_watchlist_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('watchlist_items_pkey')),
    sa.UniqueConstraint('watchlist_id', 'item_type', 'item_id', name=op.f('watchlist_items_watchlist_id_item_type_item_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_watchlist_items_list'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('origin_tracking',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('first_article_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_source_id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('first_published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('has_exact_time', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('total_coverage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('spread_hours', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('narrative_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detected_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['first_article_id'], ['articles.id'], name=op.f('origin_tracking_first_article_id_fkey')),
    sa.ForeignKeyConstraint(['first_source_id'], ['sources.source_id'], name=op.f('origin_tracking_first_source_id_fkey')),
    sa.ForeignKeyConstraint(['narrative_id'], ['narratives.id'], name=op.f('origin_tracking_narrative_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('origin_tracking_pkey'))
    )
    op.create_index(op.f('idx_origin_topic'), 'origin_tracking', ['topic'], unique=False)
    op.create_index(op.f('idx_origin_source'), 'origin_tracking', ['first_source_id'], unique=False)
    op.create_index(op.f('idx_origin_date'), 'origin_tracking', [sa.literal_column('first_published_at DESC')], unique=False)
    # ### end Alembic commands ###
